Imposed constraint update
rustls/webpki-roots pull request #36
Opened 2023-07-26 14:58 UTC by djc

Happened to find this change somewhat randomly:

https://hg.mozilla.org/projects/nss/rev/023f640c52040ff02bdd3c44df2b5ae927fa9e4f
https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/DotaWOS0v1E/m/icFj9tAzBQAJ
https://bugzilla.mozilla.org/show_bug.cgi?id=1802944

Propose to publish yet another release after this is merged.

2023-07-26 15:35 UTC, cpu approved these changes
Nice spot

2023-07-26 16:09 UTC, djc commented
I was looking at that earlier. Using that would enable noticing changes, but going from `*.tr` to the constraints encoding would be a manual step. For now, I've subscribed to https://hg.mozilla.org/projects/nss/atom-log/tip/lib/certdb/genname.c in my RSS reader.

2023-07-26 16:13 UTC, cpu commented
> but going from *.tr to the constraints encoding would be a manual step. 

Why is that?

2023-07-27 10:06 UTC, ctz commented
> Why is that?

I guess we'd need to write an encoder to put these strings into the form of a `NameConstraints` extension body, but that is definitely doable?

2023-07-27 10:20 UTC, ctz commented
Way back I had added a test for this root's constraints -- unfortunately I never landed it because the test failed, because the webpki crate didn't have working name constraints support back then. That is fixed since January. The old commit is here: https://github.com/rustls/webpki-roots/commit/65282d9f07f46d9f272c82034811f9155920844b - unfortunately only a positive test.

2023-07-27 11:10 UTC, ctz requested changes

2023-07-27 11:10 UTC, ctz commented on tests/codegen.rs
> +const TUBITAK1_NAME_CONSTRAINTS: &[&[u8]] = &[b"\x30\x09\xa0\x07", b"\x30\x05\x82\x03", b".tr"];
I think this wants 0xa0, 0x0b on  the front.

- 0xa0  = `CONTEXT_SPECIFIC 0 | CONSTRUCTED`)
- 0x0b  = 11 bytes length

2023-07-27 11:57 UTC, cpu commented
> I guess we'd need to write an encoder to put these strings into the form of a NameConstraints extension body, but that is definitely doable?

That's what I was thinking but wasn't sure if I was overlooking some inherent ambiguity that would make it harder than it seems.

2023-07-27 12:50 UTC, djc commented
> Way back I had a test for this root's constraints -- unfortunately I never landed it because the test failed, because the webpki crate didn't have working name constraints support back then. That is fixed since January. The old commit is here: [65282d9](https://github.com/rustls/webpki-roots/commit/65282d9f07f46d9f272c82034811f9155920844b) - unfortunately only a positive test.

Oh great -- that was pretty easy to rebase onto the current state of affairs, and allowed me to verify that your suggested fix works.

2023-07-27 12:52 UTC, ctz approved these changes

2023-07-27 12:52 UTC, cpu approved these changes

2023-07-27 12:54 UTC, merged

2023-07-27 12:55 UTC, djc commented
Published 0.25.1.